# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotImageGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import numpy as np
from scipy.ndimage import gaussian_filter


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout.addWidget(self.pushButton_plot)
        self.pushButton_filter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.horizontalLayout.addWidget(self.pushButton_filter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = ImageView(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_plot.setText(_translate("MainWindow", "Plot"))
        self.pushButton_filter.setText(_translate("MainWindow", "Filter"))
from pyqtgraph import ImageView


class MyMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        # Instancia Ui_MainWindow definida arriba
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Conectar botones
        self.ui.pushButton_plot.clicked.connect(self.plot_image)
        self.ui.pushButton_filter.clicked.connect(self.apply_filter)

        self.image_data = None

    def plot_image(self):
        self.image_data = np.random.rand(512, 512)
        self.ui.widget.setImage(self.image_data)

    def apply_filter(self):
        if self.image_data is not None:
            filtered = gaussian_filter(self.image_data, sigma=2)
            self.ui.widget.setImage(filtered)
        else:
            print("Primero debes plotear una imagen.")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MyMainWindow()
    window.show()
    sys.exit(app.exec_())

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
